apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "project-novis.fullname" . }}-superuser
  labels:
    helm.sh/chart: {{ include "project-novis.chart" . }}
    app.kubernetes.io/version: {{ .Values.application.version }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    track: "{{ .Values.application.track }}"
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-delete-policy": hook-succeeded
    "helm.sh/hook-weight": "20"
spec:
  template:
    metadata:
      name: {{ include "project-novis.fullname" . }}-superuser
      labels:
        app.kubernetes.io/name: {{ include "project-novis.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        track: "{{ .Values.application.track }}"
    spec:
      restartPolicy: Never
      containers:
      - name: {{ include "project-novis.fullname" . }}-superuser
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        args: ["createsuperuser"]
        envFrom:
          - configMapRef:
              name: {{ include "project-novis.fullname" . }}
          - secretRef:
              name: {{ include "project-novis.fullname" . }}
