{{- if .Values.ingress.enabled -}}
{{- $fullName := include "project-novis.fullname" . -}}
{{- $ingressPaths := .Values.ingress.paths -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    app.kubernetes.io/name: {{ include "project-novis.name" . }}
    app.kubernetes.io/version: {{ .Values.application.version }}
    helm.sh/chart: {{ include "project-novis.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    track: {{ .Values.application.track }}
    app: {{ template "project-novis.appname" . }}
  annotations:
    prometheus.io/probe: "true"
    nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_set_headers "Feature-Policy: geolocation 'none'; midi 'none'; notifications 'none'; push 'none'; sync-xhr 'none'; microphone 'none'; camera 'none'; magnetometer 'none'; gyroscope 'none'; speaker 'none'; vibrate 'none'; fullscreen 'none'; payment 'none'; xr 'none'; usb 'none'; autoplay 'none'; legacy-image-formats 'none'; wake-lock 'none'";
    {{- if and .Values.ingress.tls .Values.ingress.reportURI }}
      more_set_headers 'Expect-CT: max-age=86400, enforce, report-uri="{{ .Values.ingress.reportURI }}"';
    {{- else if .Values.ingress.tls }}
      more_set_headers 'Expect-CT: max-age=86400, enforce';
    {{- end }}
  {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
{{- if .Values.ingress.tls }}
  tls:
    - hosts:
        - {{ .Values.ingress.host | quote }}
      secretName: {{ .Values.ingress.host }}-tls
{{- end }}
  rules:
    - host: {{ .Values.ingress.host | quote }}
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ $fullName }}
              servicePort: http
{{- end }}
