apiVersion: v1
kind: Secret
metadata:
  name: {{ include "project-novis.fullname" . }}
type: Opaque
data:
  DATABASE_URL: {{ .Values.django.databaseURL | b64enc | quote }}
  {{- if .Values.django.secretKey }}
  DJANGO_SECRET_KEY: {{ .Values.django.secretKey | b64enc | quote }}
  {{- else }}
  DJANGO_SECRET_KEY: {{ randAlphaNum 128 | b64enc | quote }}
  {{- end }}
  DJANGO_SUPERUSER_EMAIL: {{ .Values.django.superuser.email | b64enc | quote }}
  {{- if .Values.django.superuser.password }}
  DJANGO_SUPERUSER_PASSWORD: {{ .Values.django.superuser.password | b64enc | quote }}
  {{- else }}
  DJANGO_SUPERUSER_PASSWORD: {{ randAlphaNum 16 | b64enc | quote }}
  {{- end }}
  DJANGO_SENTRY_DSN: {{ .Values.django.sentry.dsn | b64enc | quote }}
  DJANGO_EMAIL_HOST_PASSWORD: {{ .Values.django.email.password | b64enc | quote }}
